#  Speaker

#  led   GPIO14   bl

#  LRC   GPIO11   pk
#  BLC   GPIO9    ye
#  Dout  GPIO7    vi

substitutions:

  name: media-player
  friendly_name: Media Player 
  i2s_lrclk: GPIO11
  i2s_bclk: GPIO09
  spk: GPIO07
  ledpin: GPIO48   #14
  ota_password: "stuff"
  key_encryption: "stuff"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_2: !secret wifi_ssid_5
  wifi_password_2: !secret wifi_password_5
  red: 100%
  green: 0%
  blue: 0% 

packages:
  va: !include common/media-player.yaml

